REPORT Z_SCREENS_1.

TABLES: ZEMPLOYEES.

DATA: WA_EMPLOYEES    LIKE ZEMPLOYEES-EMPLOYEE.

PARAMETERS: MY_EE     LIKE ZEMPLOYEES-EMPLOYEE DEFAULT '12345678'.

SELECTION-SCREEN BEGIN OF BLOCK MYBLOCK1 WITH FRAME TITLE TEXT-001.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION POS_LOW.
PARAMETER ABC(5).
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN COMMENT 01(15) TEXT-001.
SELECTION-SCREEN COMMENT 20(15) COMM1.

SELECTION-SCREEN END OF BLOCK MYBLOCK1.

SELECTION-SCREEN SKIP 2.

PARAMETERS:
            WA_GREEN  RADIOBUTTON GROUP GRP1,
            WA_BLUE   RADIOBUTTON GROUP GRP1,
            WA_YELOW  RADIOBUTTON GROUP GRP1.

SELECT-OPTIONS MY_DOB FOR ZEMPLOYEES-DOB.

INITIALIZATION.

  COMM1 = 'Hello SAP'.

  SELECT * FROM ZEMPLOYEES.
    WA_EMPLOYEES = ZEMPLOYEES-EMPLOYEE.
  ENDSELECT.

AT SELECTION-SCREEN ON MY_EE.
* Check to make sure employee number is not greater than
* last employee number in zemployees table.

  IF MY_EE > WA_EMPLOYEES.
    MESSAGE E001(ZMES1) WITH MY_EE.
  ENDIF.

***************************************
* Select with Loop

  SELECT * FROM ZEMPLOYEES.
    IF ZEMPLOYEES-DOB IN MY_DOB.
      WRITE: / ZEMPLOYEES.
    ENDIF.
  ENDSELECT.

  WRITE: / 'Surname'.
  WRITE: / TEXT-001.
