REPORT Z_SHAPESHIFTER.

************************************************************************
* Field Symbols

TYPES: BEGIN OF DATA_TYPE,
       PERNR LIKE PA0000-PERNR,
       SNAME LIKE PA0001-SNAME,
       END OF DATA_TYPE.

DATA: MAIN_DATA TYPE DATA_TYPE OCCURS 0 WITH HEADER LINE.
FIELD-SYMBOLS: <FS_MAIN_DATA> TYPE DATA_TYPE.

START-OF-SELECTION.

  SELECT DISTINCT PERNR
    FROM PA0000
    INTO TABLE MAIN_DATA.

  SORT MAIN_DATA BY PERNR ASCENDING.

END-OF-SELECTION.

*Note: The use of the field symbol eliminates the need to do a MODIFY statement
*Note: This also eliminates use of the table header record - the field symbol REPLACES it.

  LOOP AT MAIN_DATA ASSIGNING <FS_MAIN_DATA>.
    CLEAR <FS_MAIN_DATA>-SNAME.
    SELECT SINGLE SNAME
      FROM PA0001
      INTO <FS_MAIN_DATA>-SNAME
     WHERE PERNR = <FS_MAIN_DATA>-PERNR
       AND ENDDA = '99991231'.
    IF <FS_MAIN_DATA>-SNAME IS INITIAL.
      MOVE 'None' TO <FS_MAIN_DATA>-SNAME.
    ENDIF.
  ENDLOOP.

  SORT MAIN_DATA BY PERNR ASCENDING.

  LOOP AT MAIN_DATA ASSIGNING <FS_MAIN_DATA>.
    WRITE: / <FS_MAIN_DATA>-PERNR, <FS_MAIN_DATA>-SNAME.
  ENDLOOP.
